package com.financematch.recommendation.type;

public enum RecommendationReasonCode {
    DEPOSIT_TERM_AND_RATE,
    SAVINGS_KB_STAR_PRIORITY,
    SAVINGS_TERM_AND_RATE,
    INVESTMENT_RETIREMENT_TDF_PRIORITY,
    INVESTMENT_RISK_AND_AUM,
    LOAN_TARGET_GROUP_RATE_AND_CHANNEL,
    TAX_SAVING_ISA_KNOWLEDGE,
    TAX_SAVING_PENSION_RETIREMENT,
    TAX_SAVING_IRP_INVESTMENT_TYPE
}